services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - dostavka

  # php, composer, supervisor, horison
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    networks:
      - dostavka
    depends_on:
      - mysql
      - redis
      - mailhog

  mysql:
    image: mysql:8.4
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - dostavka

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - ./docker/redis:/data
    networks:
      - dostavka
    command: >
      sh -c " chown -R redis:redis /data && chmod -R 755 /data && redis-server --appendonly yes --stop-writes-on-bgsave-error no "
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - dostavka

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
    depends_on:
      - mysql
    networks:
      - dostavka

  horizon:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - APP_NAME=$(APP_NAME)
      - APP_ENV=$(APP_ENV)
      - APP_KEY=$(APP_KEY)
      - APP_DEBUG=$(APP_DEBUG)
      - APP_URL=$(APP_URL)
      - DB_CONNECTION=$(DB_CONNECTION)
      - DB_HOST=$(DB_HOST)
      - DB_PORT=$(DB_PORT)
      - DB_DATABASE=$(DB_DATABASE)
      - DB_USERNAME=$(DB_USERNAME)
      - DB_PASSWORD=$(DB_PASSWORD)
      - REDIS_HOST=$(REDIS_HOST)
      - REDIS_PORT=$(REDIS_PORT)
      - QUEUE_CONNECTION=$(QUEUE_CONNECTION)
      - HORIZON_DASHBOARD_SECRET=secret
    depends_on:
      - redis
    networks:
      - dostavka
    command: php artisan horizon

networks:
  dostavka:
    driver: bridge

# https://howto.im/q/how-to-deploy-laravel-horizon-using-docker
# https://www.youtube.com/watch?v=R-ALpRFmiAU
